create schema if not exists "MY_BLOG";
set schema "MY_BLOG";

drop table if exists comments;
drop table if exists posts;

create table posts
(
    id          bigint generated by default as identity primary key,
    title       varchar(1000),
    text        clob,
    tags        varchar array,
    likes_count integer default 0,
    file_name   varchar(1000)
);

create table comments
(
    id      bigint generated by default as identity primary key,
    text    clob,
    post_id bigint references posts (id)
);

