create schema if not exists "MY_BLOG";
set schema "MY_BLOG";

drop table if exists comments;
drop table if exists posts;

create table posts
(
    id          bigint generated by default as identity primary key,
    title       varchar(1000) not null,
    text        clob          not null,
    tags        varchar array not null default '{}',
    likes_count integer                default 0,
    file_name   varchar(1000)
);

create index idx_posts_title on posts(title);
create index idx_posts_tags on posts(tags);

create table comments
(
    id      bigint generated by default as identity primary key,
    text    clob not null,
    post_id bigint references posts (id)
);

